version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    ktsu:
      patterns:
        - "ktsu.*"
    Microsoft:
      patterns:
        - "Microsoft.*"
    System:
      patterns:
        - "System.*"
    Silk:
      patterns:
        - "Silk.NET.*"