on:
  workflow_call:

jobs:
  release:
    steps:
      - name: Commit
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update VERSION to ${{ env.VERSION }}'
          file_pattern: 'VERSION'
        
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.*nupkg"
          tag: v${{ env.VERSION }}
          commit: ${{ steps.auto-commit-action.outputs.commit_hash }}
          allowUpdates: false
          skipIfReleaseExists: true
          omitBody: true
          generateReleaseNotes: true
          replacesArtifacts: false
          makeLatest: true
