on:
  workflow_call:

jobs:
  version:
    steps:
      - name: Read version
        id: versionfile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION
          trim: true

      - name: Bump version
        id: semver
        uses: nguyenvukhang/semver-increment@v1
        with:
          increment: ${{ contains(steps.versionfile.outputs.content, 'alpha') && 'prerelease' || 'patch' }}
          identifier: 'alpha'
          version-file: 'VERSION'
          version-regex: '^(.*)'

      - name: Return version
        run: |
          "VERSION=${{ steps.semver.outputs.version }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append